### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by erwinpalma** [kb-software/jbtpdf01#3]
- [ ] create the query for sql
- [ ] create the csv files based on the output
- [ ] Fix the numbers issue
- [ ] read and write the wkn, country & share
